-- 임베디드 모드로 실행 할때는 실행 할때마다 테이블을 생성해줘야함 -> 해당 경로에 schema.sql 파일을 정의해줘야함
drop table if exists item CASCADE;
CREATE TABLE item (
                      id        bigint generated by default as identity,
                      item_name     VARCHAR(10),
                      price    integer,
                      quantity   integer,
                      PRIMARY KEY(id)
);